### ISSUE TITLE
Magpie throws an exception when adding an entry over SSH (No X forwarding)

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/magpie#2]
Traceback (most recent call last):
  File "magpie.py", line 381, in <module>
    main( options, args )
  File "magpie.py", line 192, in main
    clipboard.write( requested )
  File "magpie.py", line 339, in write
    proc.stdin.write( text )
IOError: [Errno 32] Broken pipe

**Comment by mcgrew** [comment]
This was fixed at some point in the last 10 years. Closing.
